In [1]:
import pandas as pd

In [2]:
df1  = pd.read_csv("titanic.csv")
print(df1.head(2))
print("\n")
print(df1.tail(2))

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False


     survived  pclass   sex   age  sibsp  parch   fare embarked  class  who  \
889         1       1  male  26.0      0      0  30.00        C  First  man
890         0       3  male  32.0      0      0   7.75        Q  Third  man

     adult_male deck embark_town alive  alone
889        True    C   Cherbourg   yes   True
890        True  NaN  Queenstown    no   True

In [5]:
print(f"info : \n{df1.info()} \n")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB
info :
None

In [6]:

print(f"columns : \n{df1.columns} \n")

columns :
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [7]:
print(df1.describe()) # to get the statistical data of numerical columns

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [17]:
import pandas as pd

df = pd.read_csv("titanic.csv")

# Select specific columns
print(df[["survived", "pclass"]].head())

print("\n")

print(f"data tpyes of the subsets : \n {df[['survived', 'pclass']].dtypes}")

   survived  pclass
0         0       3
1         1       1
2         1       3
3         1       1
4         0       3


data tpyes of the subsets :
 survived    int64
pclass      int64
dtype: object

In [18]:
# the similar thing can be achived using : 
import pandas as pd

df = pd.read_csv("titanic.csv")

# Create a new DataFrame with only 'survived' and 'pclass'
new_df = df[["survived", "pclass"]]

print(new_df.head())
print(type(new_df))
print(f"data tpyes of the subsets : \n {new_df.dtypes}")

   survived  pclass
0         0       3
1         1       1
2         1       3
3         1       1
4         0       3
<class 'pandas.core.frame.DataFrame'>
data tpyes of the subsets :
 survived    int64
pclass      int64
dtype: object

In [22]:
df = pd.read_csv("titanic.csv")

print(df.dtypes == 'object')  # Check which columns are of type 'object' >> returns a boolean Series ( true if object is string)
print("\n")
print(df.dtypes[df.dtypes == 'object'])  # to get the columns which are of type object

# now to print exact column names of type object
print("\n")
print(df.dtypes[df.dtypes == 'object'].index)  # to get the columns which are of type object

survived       False
pclass         False
sex             True
age            False
sibsp          False
parch          False
fare           False
embarked        True
class           True
who             True
adult_male     False
deck            True
embark_town     True
alive           True
alone          False
dtype: bool


sex            object
embarked       object
class          object
who            object
deck           object
embark_town    object
alive          object
dtype: object


Index(['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive'], dtype='object')

In [31]:

print(df[df.dtypes[df.dtypes == 'object'].index].head())  # to get the columns which are of type object
print("\n")
print(df[['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive']].head())
print("\n")
print(df.select_dtypes(include=['object']).head())  # to get the columns which are of type object

      sex embarked  class    who deck  embark_town alive
0    male        S  Third    man  NaN  Southampton    no
1  female        C  First  woman    C    Cherbourg   yes
2  female        S  Third  woman  NaN  Southampton   yes
3  female        S  First  woman    C  Southampton   yes
4    male        S  Third    man  NaN  Southampton    no


      sex embarked  class    who deck  embark_town alive
0    male        S  Third    man  NaN  Southampton    no
1  female        C  First  woman    C    Cherbourg   yes
2  female        S  Third  woman  NaN  Southampton   yes
3  female        S  First  woman    C  Southampton   yes
4    male        S  Third    man  NaN  Southampton    no


      sex embarked  class    who deck  embark_town alive
0    male        S  Third    man  NaN  Southampton    no
1  female        C  First  woman    C    Cherbourg   yes
2  female        S  Third  woman  NaN  Southampton   yes
3  female        S  First  woman    C  Southampton   yes
4    male        S  Third    man  NaN  Southampton    no

In [32]:
df.describe(include=['object'])  # to get the statistical data of object type columns

         sex embarked  class  who deck  embark_town alive
count    891      889    891  891  203          889   891
unique     2        3      3    3    7            3     2
top     male        S  Third  man    C  Southampton    no
freq     577      644    491  537   59          644   549

In [33]:
df.describe(include= 'all')  # to get the statistical data of object type columns

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
import pandas as pd
df_students = pd.read_excel("students.xlsx")
print(df_students.head())

# creatig a new column year of degree 
df_students["Result"] = df_students["Score"].apply(lambda x: "Pass" if x >= 40 else "Fail")
print(df_students.head())

   StudentID    Name  Age Department  Score
0        101   Parth   21         CS     88
1        102  Mikasa   20         IT     92
2        103   Armin   22        ECE     95
3        104    Eren   19       MECH     70
4        105    Levi   30         CS     99
   StudentID    Name  Age Department  Score Result
0        101   Parth   21         CS     88   Pass
1        102  Mikasa   20         IT     92   Pass
2        103   Armin   22        ECE     95   Pass
3        104    Eren   19       MECH     70   Pass
4        105    Levi   30         CS     99   Pass

In [18]:
import pandas as pd

# Load Titanic dataset
df_titanic = pd.read_csv("titanic.csv")

# 1. Convert 'pclass' to categorical
print("Categorical representation of 'pclass':")
print(pd.Categorical(df_titanic["pclass"]))
print("\n")

# 2. Find unique values in 'sex' column
print("Unique values in 'sex' column:")
print(df_titanic["sex"].unique())
print("\n")

# 3. Count frequency of each class in 'pclass'
print("Count of each category in 'pclass':")
print(df_titanic["pclass"].value_counts())
print("\n")

# 4. Percentage distribution of each class
print("Percentage of each class (normalized):")
print(df_titanic["pclass"].value_counts(normalize=True) * 100)  # multiply by 100 to see %

Categorical representation of 'pclass':
[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]


Unique values in 'sex' column:
['male' 'female']


Count of each category in 'pclass':
pclass
3    491
1    216
2    184
Name: count, dtype: int64


Percentage of each class (normalized):
pclass
3    55.106622
1    24.242424
2    20.650954
Name: proportion, dtype: float64

In [22]:
# lets solve some questions 
# Q1. How many persone of age less than 18 are there in the dataset ?
import pandas as pd
df = pd.read_csv("titanic.csv")
print(df[df["age"] < 18])
print("\n count of persons with age less than 18 : ", len(df[df["age"] < 18]))
#or you can use .shape 
print("\n count of persons with age less than 18 : ", df[df["age"] < 18].shape[0])

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
7           0       3    male   2.0      3      1  21.0750        S   Third
9           1       2  female  14.0      1      0  30.0708        C  Second
10          1       3  female   4.0      1      1  16.7000        S   Third
14          0       3  female  14.0      0      0   7.8542        S   Third
16          0       3    male   2.0      4      1  29.1250        Q   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
850         0       3    male   4.0      4      2  31.2750        S   Third
852         0       3  female   9.0      1      1  15.2458        C   Third
853         1       1  female  16.0      0      1  39.4000        S   First
869         1       3    male   4.0      1      1  11.1333        S   Third
875         1       3  female  15.0      0      0   7.2250        C   Third

       who  adult_male deck  embark_town alive  alone
7    child       False  NaN  Southampton    no  False
9    child       False  NaN    Cherbourg   yes  False
10   child       False    G  Southampton   yes  False
14   child       False  NaN  Southampton    no   True
16   child       False  NaN   Queenstown    no  False
..     ...         ...  ...          ...   ...    ...
850  child       False  NaN  Southampton    no  False
852  child       False  NaN    Cherbourg    no  False
853  woman       False    D  Southampton   yes  False
869  child       False  NaN  Southampton   yes  False
875  child       False  NaN    Cherbourg   yes   True

[113 rows x 15 columns]

 count of persons with age less than 18 :  113

 count of persons with age less than 18 :  113

In [3]:
#Que 2. Name of the passenger who is less than 10years old 
import pandas as pd
df = pd.read_csv("titanic.csv")
print(df[df["age"] < 10].Name)
#or we can use dot notation
print(df[df.age < 10].name)

AttributeError: 'DataFrame' object has no attribute 'Name'

In [25]:
# Que 3. How many peopel paid less thand average fair 
print("\n average fair is : ", df["fare"].mean())
print(df[df["fare"] < df["fare"].mean()])
print("\n count of person who paid less than average fair: ", len(df[df["fare"] < df["fare"].mean()]))

 average fair is :  32.204207968574636
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
2           1       3  female  26.0      0      0   7.9250        S   Third
4           0       3    male  35.0      0      0   8.0500        S   Third
5           0       3    male   NaN      0      0   8.4583        Q   Third
7           0       3    male   2.0      3      1  21.0750        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
2    woman       False  NaN  Southampton   yes   True
4      man        True  NaN  Southampton    no   True
5      man        True  NaN   Queenstown    no   True
7    child       False  NaN  Southampton    no  False
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[680 rows x 15 columns]

 count of person who paid less than average fair:  680

In [5]:
# Que4. How many pessengers are male
print(df[df["sex"] == "male"])
len(df[df["sex"] == "male"])

     survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
0           0       3  male  22.0      1      0   7.2500        S   Third
4           0       3  male  35.0      0      0   8.0500        S   Third
5           0       3  male   NaN      0      0   8.4583        Q   Third
6           0       1  male  54.0      0      0  51.8625        S   First
7           0       3  male   2.0      3      1  21.0750        S   Third
..        ...     ...   ...   ...    ...    ...      ...      ...     ...
883         0       2  male  28.0      0      0  10.5000        S  Second
884         0       3  male  25.0      0      0   7.0500        S   Third
886         0       2  male  27.0      0      0  13.0000        S  Second
889         1       1  male  26.0      0      0  30.0000        C   First
890         0       3  male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
4      man        True  NaN  Southampton    no   True
5      man        True  NaN   Queenstown    no   True
6      man        True    E  Southampton    no   True
7    child       False  NaN  Southampton    no  False
..     ...         ...  ...          ...   ...    ...
883    man        True  NaN  Southampton    no   True
884    man        True  NaN  Southampton    no   True
886    man        True  NaN  Southampton    no   True
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[577 rows x 15 columns]

577

In [29]:
print(df[df["pclass"] == 1])
print(len(df[df["pclass"] == 1]))

     survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First
3           1       1  female  35.0      1      0  53.1000        S  First
6           0       1    male  54.0      0      0  51.8625        S  First
11          1       1  female  58.0      0      0  26.5500        S  First
23          1       1    male  28.0      0      0  35.5000        S  First
..        ...     ...     ...   ...    ...    ...      ...      ...    ...
871         1       1  female  47.0      1      1  52.5542        S  First
872         0       1    male  33.0      0      0   5.0000        S  First
879         1       1  female  56.0      0      1  83.1583        C  First
887         1       1  female  19.0      0      0  30.0000        S  First
889         1       1    male  26.0      0      0  30.0000        C  First

       who  adult_male deck  embark_town alive  alone
1    woman       False    C    Cherbourg   yes  False
3    woman       False    C  Southampton   yes  False
6      man        True    E  Southampton    no   True
11   woman       False    C  Southampton   yes   True
23     man        True    A  Southampton   yes   True
..     ...         ...  ...          ...   ...    ...
871  woman       False    D  Southampton   yes  False
872    man        True    B  Southampton    no   True
879  woman       False    C    Cherbourg   yes  False
887  woman       False    B  Southampton   yes   True
889    man        True    C    Cherbourg   yes   True

[216 rows x 15 columns]
216

In [ ]:
# how many female paid more thatn average fare
avg = df["age"].mean()
print((df["sex"] ==  "female") & (df["age"] > avg))
len((df["sex"] ==  "female") & (df["age"] > avg))

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

891

In [6]:
#calculate mean using numpy 
import numpy as np
mean_age = np.mean(df["age"])
print("mean age using numpy is : ", mean_age)

mean age using numpy is :  29.69911764705882

In [9]:
# people who paid max fair 
max_fare = df["fare"].max()
print("max fare is : ", max_fare)
print(df[df["fare"] == max_fare])

max fare is :  512.3292
     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
258         1       1  female  35.0      0      0  512.3292        C  First
679         1       1    male  36.0      0      1  512.3292        C  First
737         1       1    male  35.0      0      0  512.3292        C  First

       who  adult_male deck embark_town alive  alone
258  woman       False  NaN   Cherbourg   yes   True
679    man        True    B   Cherbourg   yes  False
737    man        True    B   Cherbourg   yes   True